go ahead and (re)quell the warning about not being able to determine bold mode
svn:revision:27120
cvs:account:brlcad
cvs:branch:trunk

diff --git a/sh/shtool b/sh/shtool
--- a/sh/shtool
+++ b/sh/shtool
@@ -498,7 +498,7 @@ echo )
                 ;;
         esac
         if [ ".$term_bold" = . ] || [ ".$term_norm" = . ]; then
-            echo "$msgprefix:Warning: unable to determine terminal sequence for bold mode" 1>&2
+#            echo "$msgprefix:Warning: unable to determine terminal sequence for bold mode" 1>&2
             term_bold=''
             term_norm=''
         fi
