*** empty log message ***
svn:revision:20935
cvs:account:morrison
cvs:branch:trunk

diff --git a/regress/tests.d/library b/regress/tests.d/library
--- a/regress/tests.d/library
+++ b/regress/tests.d/library
@@ -732,7 +732,7 @@ releaseAllSemaphores ( ) {
 # attachmentTupleList is a 2-tuple pair of 'filename' and 'label' that will be attached
 #   as a mime text attachment, single quote wrapping and label are both required
 #   e.g. $4="'file1' 'label1' 'file2' 'label2' 'file3' 'label3' "
-###
+#
 mail ( ) {
     if [ ! "x$DEBUG" = "x" ] ; then log "mail( \$1=[$1] \$2=[$2] \$3=[$3] \$4=[$4])" ; fi
 
@@ -1034,13 +1034,15 @@ case $0 in
         initializeVariable LPWD "`dirname $0`" ;;
     # relative path to sourcing script
     */* )
-        initializeVariable LPWD "`pwd`/`dirname $0`" ;;
+        initializeVariable PWD "`pwd`" # this is to avoid the freebsd /bin/sh pwd problem
+        initializeVariable LPWD "$PWD/`dirname $0`" ;;
     # sourcing script is in the path
     * )
-        initializeVariable LPWD "`pwd`" ;;
+        initializeVariable PWD "`pwd`" # this is to avoid the freebsd /bin/sh pwd problem
+        initializeVariable LPWD "$PWD" ;;
 esac
 if [ ! -f "$LPWD/library" ] ; then
-    warn "Unable to properly initialize path to library source varaible [LPWD]"
+    warn "Unable to properly initialize path to library source varaible [LPWD=$LPWD]"
 fi
 
 # set STYLE value to 'color' to invoke color logging output, set to anything
@@ -1058,3 +1060,126 @@ SETCOLOR_FAILURE="echo -en \\033[1;31m"
 SETCOLOR_WARNING="echo -en \\033[1;33m"
 # terminal sequence to reset to the default color.
 SETCOLOR_NORMAL="echo -en \\033[0;39m"
+
+
+
+# REGRESSION TEST SPECIFIC
+###
+
+TEST_WITH_PATH="$0"
+initializeVariable TEST "`echo $0 | sed 's/^.*\/\(.*\)$/\1/'`"
+initializeVariable TEST "$0"
+initializeVariable TEST "test"
+initializeVariable NAME "$TEST"
+
+
+initializeTest ( ) { 
+
+    # if regress_dir was not set, default to the package that this script is included with
+    initializeVariable PACKAGE_NAME .
+    if [ "x$REGRESS_DIR" = "x" ] ; then
+        if [ -d "$LPWD/../../../$PACKAGE_NAME" ] ; then
+            initializeVariable REGRESS_DIR "$LPWD/../../.."
+        elif [ -d "$LPWD/../../$PACKAGE_NAME" ] ; then
+            initializeVariable REGRESS_DIR "$LPWD/../.."
+        elif [ -d "$LPWD/../$PACKAGE_NAME" ] ; then
+            initializeVariable REGRESS_DIR "$LPWD/.."
+        elif [ -d "$LPWD/$PACKAGE_NAME" ] ; then
+            initializeVariable REGRESS_DIR "$LPWD"
+        else
+            warn "Unable to locate $PACKAGE_NAME"
+        fi
+    fi
+    
+    return 0
+}
+
+
+#
+# Default start function must be overridden in order for any of these
+# scripts to work.  It's the only required function, since the rest is
+# handled by bookkeeping behind the scenes.
+#
+start ( ) { 
+    bomb "start function must be implemented for $TEST"
+}
+
+#
+# This curious little oddity is neccessary only because a few misbehaving
+# shells include built-in aliases named "stop" (irix).  And since the 
+# behaviour of the built-in "." source command on that same platform 
+# reads in and preprocesses the file beforehand, it's not possible to
+# unalias the alias in order to define a stub function. 
+# 
+# Hence the solution in use here is to use alternate stub functions and
+# then test at runtime whether the user defined the appropriate function.
+# If they did, we use it, if not, we use the "default" behaviour defined
+# here.
+#
+_stop ( ) {
+    log "Stopping $TEST"
+    return 0
+}
+_status ( ) {
+    log "Checking $TEST status"
+    return 0
+}
+_clean ( ) {
+    log "Cleaning $TEST"
+    return 0
+}
+
+unalias start
+unalias stop
+unalias restart
+unalias status
+unalias clean
+unset start
+unset stop
+unset restart
+unset status
+unset clean
+
+
+#
+# regress
+#
+# This is the primary regression test control function that user scripts 
+# get to call for convenience to assure consistent behaviour.  User
+# functions may override any of the control functions (start, stop, etc)
+# and even not use this function if alternate behaviour is desired.
+# Doing so may impact the master regresssion script.
+#
+regress ( ) {
+
+    case "$1" in
+        start )
+            initializeTest
+            eval start
+            ;;
+        stop )
+            initializeTest
+            eval _stop
+            exec stop > /tmp/${TEST}.stop 2>&1
+            ;;
+        restart )
+            initializeTest
+            eval _stop
+            eval start
+            ;;
+        status )
+            initializeTest
+            eval _status
+            ;;
+        clean )
+            initializeTest
+            eval _clean
+            ;;
+        * )
+            log "Usage: $TEST_WITH_PATH {start|stop|restart|status|clean}"
+            return 1
+    esac
+
+    return $?
+}
+
